services:
  - type: web
    name: cocreation-dashboard
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SHEET_ID
        sync: false